//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDona.Relatorios.Web.LojaReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatatablesModelDTO", Namespace="http://schemas.datacontract.org/2004/07/DDona.Relatorios.DTO.DataTables")]
    [System.SerializableAttribute()]
    public partial class DatatablesModelDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DDona.Relatorios.Web.LojaReference.DatatablesColumnModelDTO[] columnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int drawField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int lengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DDona.Relatorios.Web.LojaReference.DatatablesOrderModelDTO[] orderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DDona.Relatorios.Web.LojaReference.DatatablesColumnSearchModelDTO searchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int startField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DDona.Relatorios.Web.LojaReference.DatatablesColumnModelDTO[] columns {
            get {
                return this.columnsField;
            }
            set {
                if ((object.ReferenceEquals(this.columnsField, value) != true)) {
                    this.columnsField = value;
                    this.RaisePropertyChanged("columns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int draw {
            get {
                return this.drawField;
            }
            set {
                if ((this.drawField.Equals(value) != true)) {
                    this.drawField = value;
                    this.RaisePropertyChanged("draw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int length {
            get {
                return this.lengthField;
            }
            set {
                if ((this.lengthField.Equals(value) != true)) {
                    this.lengthField = value;
                    this.RaisePropertyChanged("length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DDona.Relatorios.Web.LojaReference.DatatablesOrderModelDTO[] order {
            get {
                return this.orderField;
            }
            set {
                if ((object.ReferenceEquals(this.orderField, value) != true)) {
                    this.orderField = value;
                    this.RaisePropertyChanged("order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DDona.Relatorios.Web.LojaReference.DatatablesColumnSearchModelDTO search {
            get {
                return this.searchField;
            }
            set {
                if ((object.ReferenceEquals(this.searchField, value) != true)) {
                    this.searchField = value;
                    this.RaisePropertyChanged("search");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int start {
            get {
                return this.startField;
            }
            set {
                if ((this.startField.Equals(value) != true)) {
                    this.startField = value;
                    this.RaisePropertyChanged("start");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatatablesColumnSearchModelDTO", Namespace="http://schemas.datacontract.org/2004/07/DDona.Relatorios.DTO.DataTables")]
    [System.SerializableAttribute()]
    public partial class DatatablesColumnSearchModelDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool regexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool regex {
            get {
                return this.regexField;
            }
            set {
                if ((this.regexField.Equals(value) != true)) {
                    this.regexField = value;
                    this.RaisePropertyChanged("regex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatatablesColumnModelDTO", Namespace="http://schemas.datacontract.org/2004/07/DDona.Relatorios.DTO.DataTables")]
    [System.SerializableAttribute()]
    public partial class DatatablesColumnModelDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool orderableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DDona.Relatorios.Web.LojaReference.DatatablesColumnSearchModelDTO searchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool searchableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool orderable {
            get {
                return this.orderableField;
            }
            set {
                if ((this.orderableField.Equals(value) != true)) {
                    this.orderableField = value;
                    this.RaisePropertyChanged("orderable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DDona.Relatorios.Web.LojaReference.DatatablesColumnSearchModelDTO search {
            get {
                return this.searchField;
            }
            set {
                if ((object.ReferenceEquals(this.searchField, value) != true)) {
                    this.searchField = value;
                    this.RaisePropertyChanged("search");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool searchable {
            get {
                return this.searchableField;
            }
            set {
                if ((this.searchableField.Equals(value) != true)) {
                    this.searchableField = value;
                    this.RaisePropertyChanged("searchable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatatablesOrderModelDTO", Namespace="http://schemas.datacontract.org/2004/07/DDona.Relatorios.DTO.DataTables")]
    [System.SerializableAttribute()]
    public partial class DatatablesOrderModelDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int columnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dirField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int column {
            get {
                return this.columnField;
            }
            set {
                if ((this.columnField.Equals(value) != true)) {
                    this.columnField = value;
                    this.RaisePropertyChanged("column");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dir {
            get {
                return this.dirField;
            }
            set {
                if ((object.ReferenceEquals(this.dirField, value) != true)) {
                    this.dirField = value;
                    this.RaisePropertyChanged("dir");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatatablesResponseModelDTOOfLojaDTOYsip9d3Q", Namespace="http://schemas.datacontract.org/2004/07/DDona.Relatorios.DTO.DataTables")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DDona.Relatorios.Web.LojaReference.LojaDatatablesResponseDTO))]
    public partial class DatatablesResponseModelDTOOfLojaDTOYsip9d3Q : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DDona.Relatorios.Web.LojaReference.LojaDTO[] dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int drawField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int recordsFilteredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int recordsTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DDona.Relatorios.Web.LojaReference.LojaDTO[] data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int draw {
            get {
                return this.drawField;
            }
            set {
                if ((this.drawField.Equals(value) != true)) {
                    this.drawField = value;
                    this.RaisePropertyChanged("draw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int recordsFiltered {
            get {
                return this.recordsFilteredField;
            }
            set {
                if ((this.recordsFilteredField.Equals(value) != true)) {
                    this.recordsFilteredField = value;
                    this.RaisePropertyChanged("recordsFiltered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int recordsTotal {
            get {
                return this.recordsTotalField;
            }
            set {
                if ((this.recordsTotalField.Equals(value) != true)) {
                    this.recordsTotalField = value;
                    this.RaisePropertyChanged("recordsTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LojaDatatablesResponseDTO", Namespace="http://schemas.datacontract.org/2004/07/DDona.Relatorios.DTO.Loja")]
    [System.SerializableAttribute()]
    public partial class LojaDatatablesResponseDTO : DDona.Relatorios.Web.LojaReference.DatatablesResponseModelDTOOfLojaDTOYsip9d3Q {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LojaDTO", Namespace="http://schemas.datacontract.org/2004/07/DDona.Relatorios.DTO.Loja")]
    [System.SerializableAttribute()]
    public partial class LojaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> InvestimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NotaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Investimento {
            get {
                return this.InvestimentoField;
            }
            set {
                if ((this.InvestimentoField.Equals(value) != true)) {
                    this.InvestimentoField = value;
                    this.RaisePropertyChanged("Investimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Nota {
            get {
                return this.NotaField;
            }
            set {
                if ((this.NotaField.Equals(value) != true)) {
                    this.NotaField = value;
                    this.RaisePropertyChanged("Nota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LojaReference.ILoja")]
    public interface ILoja {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoja/GetRelatorioPaginadoDatatables", ReplyAction="http://tempuri.org/ILoja/GetRelatorioPaginadoDatatablesResponse")]
        DDona.Relatorios.Web.LojaReference.LojaDatatablesResponseDTO GetRelatorioPaginadoDatatables(DDona.Relatorios.Web.LojaReference.DatatablesModelDTO DatatablesModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoja/GetRelatorioPaginadoDatatables", ReplyAction="http://tempuri.org/ILoja/GetRelatorioPaginadoDatatablesResponse")]
        System.Threading.Tasks.Task<DDona.Relatorios.Web.LojaReference.LojaDatatablesResponseDTO> GetRelatorioPaginadoDatatablesAsync(DDona.Relatorios.Web.LojaReference.DatatablesModelDTO DatatablesModel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILojaChannel : DDona.Relatorios.Web.LojaReference.ILoja, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LojaClient : System.ServiceModel.ClientBase<DDona.Relatorios.Web.LojaReference.ILoja>, DDona.Relatorios.Web.LojaReference.ILoja {
        
        public LojaClient() {
        }
        
        public LojaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LojaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LojaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LojaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DDona.Relatorios.Web.LojaReference.LojaDatatablesResponseDTO GetRelatorioPaginadoDatatables(DDona.Relatorios.Web.LojaReference.DatatablesModelDTO DatatablesModel) {
            return base.Channel.GetRelatorioPaginadoDatatables(DatatablesModel);
        }
        
        public System.Threading.Tasks.Task<DDona.Relatorios.Web.LojaReference.LojaDatatablesResponseDTO> GetRelatorioPaginadoDatatablesAsync(DDona.Relatorios.Web.LojaReference.DatatablesModelDTO DatatablesModel) {
            return base.Channel.GetRelatorioPaginadoDatatablesAsync(DatatablesModel);
        }
    }
}
